### ISSUE TITLE
Error when sending report

### ISSUE THREAD

**Issue by scottd34** [thorian93/ansible-role-upgrade#17]
I get this error when on the Send Reports by Mail step. 

`fatal: [ name -> localhost]: FAILED! => {"changed": false, "msg": "argument 'port' is of type <class 'list'> and we were unable to convert to int: <class 'list'> cannot be converted to an int"}`

I have port 587 set in the defaults/main.yml
`upgrade_reporting_mail_port: [587]`

**Comment by thorian93** [comment]
Hi @scottd34 and thanks for your patience!

Have you tried removing the brackets around the port? That should do the trick.

**Comment by scottd34** [comment]
Removing the brackets did not work, but replacing [] with "" did.  I also had to do this to two other fields
upgrade_reporting_mail_from: ""
upgrade_reporting_mail_host: ""
upgrade_reporting_mail_port: ""

The field upgrade_reporting_mail_run_once: 'true' is being ignored.  I get one email per host regardless of this setting being true or false. Tried replacing with "" with no change.

Running on Debian GNU/Linux 11 (bullseye)

Let me know what other details you need.
